sudo: false

language: node_js

matrix:
  include:
    - node_js: "node"
      env: NPM_RUN_SCRIPT=test NPM_AUDIT=true
    - node_js: "9"
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"

install:
  - npm install
  - if [ "$NPM_AUDIT" = true ]; then npm audit; fi

script:
  - npm run ${NPM_RUN_SCRIPT:-test:script}
